from tkinter import BOTTOM, CENTER, FLAT
from typing import Final


class Styles:
    PRIMARY_COLOR = "#4c75bd"
    SECONDARY_COLOR = "#F37878"
    WHITE_COLOR = "#FFFFFF"
    BLACK_COLOR = "#000000"

    FONT_POPPINS = "poppins"
    FONT_POPPINS_12 = f"{FONT_POPPINS} 12"
    FONT_POPPINS_13 = f"{FONT_POPPINS} 13"
    FONT_POPPINS_14 = f"{FONT_POPPINS} 14"
    FONT_POPPINS_15 = f"{FONT_POPPINS} 15"
    FONT_POPPINS_16 = f"{FONT_POPPINS} 16"
    FONT_POPPINS_20 = f"{FONT_POPPINS} 20"
    FONT_POPPINS_22 = f"{FONT_POPPINS} 22"
    FONT_POPPINS_40 = f"{FONT_POPPINS} 40"

    FONT_POPPINS_BOLD_25 = f"{FONT_POPPINS} 25 bold"

    CENTER: Final = CENTER

    JUSTIFY_CENTER: Final = CENTER

    SIDE_BOTTOM: Final = BOTTOM

    ANCHOR_CENTER: Final = CENTER

    RELIEF_FLAT: Final = FLAT

    CURSOR_HAND2 = "hand2"
